### ISSUE TITLE
Master branch is broken when run revel build

### ISSUE THREAD

**Issue by douglarek** [revel/revel#1014] opened 2015-12-13 07:09 UTC
When I use `revel build` with revel master branch, I got this panic: http://paste.ubuntu.com/13985995/;

And then I checkout tag v0.12.0, it works;

**Comment by littlexiang** [comment] 2015-12-14 05:39
usually it is because you are inside the project path
try this
```mkdir build```
```cd build/```
```revel build project```

**Comment by douglarek** [comment] 2015-12-14 13:04
@littlexiang thanks, `revel build`

```
~
~ revel! http://revel.github.io
~
build [import path] [target path]

Build the Revel web application named by the given import path.
This allows it to be deployed and run on a machine that lacks a Go installation.

WARNING: The target path will be completely deleted, if it already exists!

For example:

    revel build github.com/revel/samples/chat /tmp/chat
```
maybe *[target path]* should be an absolutely path; but IMO, revel should recognize a relative one.

**Comment by pedromorgan** [comment] 2016-01-04 22:21
Is this bug still valid ??

**Comment by jeevatkm** [comment] 2016-05-26 04:48
@pedromorgan this is not bug, it work as designed. @douglarek thanks for your suggestion. Yes Revel expects `target-path` as absolute path. 

I'm closing this one.

**Closed by jeevatkm** 2016-05-26 04:48 UTC
Labels: status-waiting-for-reply

**Comment by alkchr** [comment] 2016-05-26 05:01
@jeevatkm Not a high priority but I think support of relative paths is a good thing to have. Now when you're using `revel new ./path` it ignores the `./` part and creates `$GOPATH/src/path`. And when you are using `revel run ./path` it shows an error. This is something that can be improved.

**Comment by jeevatkm** [comment] 2016-05-26 05:17
@alkchr I just checked `cmd/new.go` new command needs a fix, currently it validates absolute path gives an error msg- 
```
Abort: '%s' looks like a directory.  Please provide a Go import path instead.
```
but it needs validate relative path too, **thanks for mentioning this scenario**. I'm applying a relative path check.
