### ISSUE TITLE
Route options not found

### ISSUE THREAD

**Issue by Juancesar123** [revel/revel#1350] opened 2018-07-23 15:52 UTC
hello i have a problem route options not found in revel. im using vuejs with axios.
![image](https://user-images.githubusercontent.com/16625151/43087690-a4fcbf06-8eca-11e8-8035-a648277a0bf7.png)
this is my code in file routes in revel
`GET /posts PostController.Index

POST /posts PostController.Create

PUT /posts PostController.Update

GET /posts/:id PostController.Show

DELETE /posts/:id PostController.Delete`

**Comment by notzippy** [comment] 2018-07-23 16:42
Was there any additional log messages on the server ?

**Comment by godlikemouse** [comment] 2018-10-25 22:07
You may just need to add an options handler into your routes config file.  Especially if you're trying to do a CORS request.

**Comment by notzippy** [comment] 2018-10-30 13:28
If vue.js was posting the information it would not find the route. I am closing this for now, feel free to reopen if still an issue

**Closed by notzippy** 2018-10-30 13:28 UTC

**Comment by jonathanbrenman** [comment] 2019-05-28 18:49
Hi, I have the same problem could anyone show any example about how to add options method to the router?
I'am getting 404: status=404 duration_seconds=0.0005185 method=OPTIONS start=2019/05/28 15:46:14 section=requestlog   ip=127.0.0.1 
INFO  15:46:14    app server_adapter_go.go:158: Request Stats   

I'm new in revel.

Thank you

**Comment by godlikemouse** [comment] 2019-05-28 19:20
Here's an example that might help.  I have this running in my BaseController which gets inherited by all controllers that I want to use CORS with.

```
//in BaseController

//Method for retrieving the request origin from the request referer
func (c BaseController) GetOrigin() string {
  referer := c.Request.Header.Get("Referer")
  re := regexp.MustCompile("^http[s]?\\:\\/\\/[\\w\\:\\.\\d\\-]+")
  return re.FindString(referer)
}

//CORS OPTIONS response for handling CORS preflight
func (c BaseController) Options() revel.Result {
  c.Response.Out.Header().Set("Access-Control-Allow-Origin", c.GetOrigin())
  c.Response.Out.Header().Set("Access-Control-Allow-Credentials", "true")
  c.Response.Out.Header().Set("Access-Control-Allow-Methods", "POST, GET, PUT, OPTIONS, DELETE")
  return nil
}
```

Next, in your conf/route file add:

```
OPTIONS    /*                                BaseController.Options
```

That should allow you to send an OPTIONS request and have it routed to a controller.  The response should automatically allow the origin being pulled from the request.  If you want to limit the origin, feel free to change the line containing c.GetOrigin(). Hope this helps.

**Comment by jonathanbrenman** [comment] 2019-05-28 19:48
Many thanks for your quick answer!
I've tried to reproduce your example in my code.

I' still getting Access to XMLHttpRequest at 'http://localhost:9000/player/AHSHDHSDH' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.

do you know why is it happening that?

> package controllers
> 
> import (
> 	"github.com/revel/revel"
> 	"regexp"
> )
> 
> type App struct {
> 	*revel.Controller
> }
> 
> func (c App) Index() revel.Result {
> 	return c.Render()
> }
> 
> func (c App) GetOrigin() string {
>   referer := c.Request.Header.Get("Referer")
>   re := regexp.MustCompile("^http[s]?\\:\\/\\/[\\w\\:\\.\\d\\-]+")
>   return re.FindString(referer)
> }
> 
> //CORS OPTIONS response for handling CORS preflight
> func (c App) Options() revel.Result {
>   c.Response.Out.Header().Set("Access-Control-Allow-Origin", c.GetOrigin())
>   c.Response.Out.Header().Set("Access-Control-Allow-Credentials", "true")
>   c.Response.Out.Header().Set("Access-Control-Allow-Methods", "GET,PUT,POST,DELETE,PATCH,OPTIONS")
>   return nil
> }

**Comment by godlikemouse** [comment] 2019-05-28 20:55
@jonathanbrenman What does your conf/routes file look like?

**Comment by jonathanbrenman** [comment] 2019-05-29 14:37
Hi sorry about the time here it is my app router:

```
# Routes Config
#
# This file defines all application routes (Higher priority routes first)
#

module:testrunner
# module:jobs

GET     /                                       App.Index
GET     /player/:hash                           Player.GetSettings
GET     /content/:id                            Content.GetContentData


# Ignore favicon requests
GET     /favicon.ico                            404

# Map static resources from the /app/public folder to the /public path
GET     /public/*filepath                       Static.Serve("public")

OPTIONS    /*                                   App.Options

```

**Comment by jonathanbrenman** [comment] 2019-05-29 15:26
Yes! I always kill and restart the process when I change something out of the controllers lol

**Comment by godlikemouse** [comment] 2019-05-29 15:32
Hmmm....I wonder.  Try moving the OPTIONS /* statement to be the first line in your routes conf and try that.  If that doesn't work, then let's start adding debug statements to your Options method to see if it's even being called.

**Comment by jonathanbrenman** [comment] 2019-05-29 16:35
I did that and restart the process and this what I'm getting:
```

ion=App.Options namespace=App\\ start=2019/05/29 13:34:09 status=0 section=requestlog 
INFO  13:34:13    app server_adapter_go.go:158: Request Stats                            section=requestlog ip=127.0.0.1 method=OPTIONS action=App.Options namespace=App\\ duration_seconds=0.0000759   path=/player/17VSVW1503594373 start=2019/05/29 13:34:13 status=0
INFO  13:34:13    app server_adapter_go.go:158: Request Stats                            method=OPTIONS action=App.Options namespace=App\\ start=2019/05/29 13:34:13 status=0 duration_seconds=0.0000582  path=/player/17VSVW1503594373 section=requestlog  ip=127.0.0.1
INFO  13:34:13    app server_adapter_go.go:158: Request Stats                            namespace=App\\ start=2019/05/29 13:34:13 section=requestlog  ip=127.0.0.1 action=App.Options status=0 duration_seconds=0.0000557  path=/player/PVAZPK1542995892 method=OPTIONS
```

**Comment by godlikemouse** [comment] 2019-05-29 17:15
OK, that looks correct.  Can you verify that your routing is correct to the controller itself by adding output statements to the Options method?  Either log them or console out is fine, just to ensure it's making it to the Options method of your App controller.  Also, in your web console under network, what does the request and response look like for a valid action using CORS?  In otherwords, if you send a request to a method that exists in your App controller, say Ping() that writes out "Pong" or something.  What does the request and response look like for CORS preflight OPTIONS request?

**Comment by jonathanbrenman** [comment] 2019-05-29 17:26
I added to Options function: fmt.Println("do i actually called?"), and it is not working, like the options function is blocked out by the cors.

![Screen Shot 2019-05-29 at 14 25 29](https://user-images.githubusercontent.com/24918136/58577814-a8d98180-821d-11e9-8b54-8fe2ab128e29.png)


Access to XMLHttpRequest at 'http://localhost:9000/player/17VSVW1503594373?external_playlist=168,166,171' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by jonathanbrenman** [comment] 2019-05-29 17:27
![Screen Shot 2019-05-29 at 14 26 59](https://user-images.githubusercontent.com/24918136/58577871-d7575c80-821d-11e9-97f4-d103f7fdfc3d.png)

Here other pic

**Comment by jonathanbrenman** [comment] 2019-05-29 17:35
Ok, I found the problem now!!! the issue was now on the client side I was doing the request with this xmlhttp.setRequestHeader('Content-Type', 'application/json') and for go i don't need it because it is already responded a json.

But you still helped me with the options cors!
Thank you very much for your help!!

**Comment by godlikemouse** [comment] 2019-05-29 17:38
Okay, great. Glad you found the issue. Have a good one.
