### ISSUE TITLE
Too many open files - connections do not close

### ISSUE THREAD

**Issue by opennota** [revel/revel#837] opened 2015-01-03 17:35 UTC
I run out of open files limit (1024 files), because the connections seem to not close. A part of `lsof -n -p PID` output follows:

    opennota 16458 opennota   71u  IPv6 43159075      0t0    TCP [myserver]:9000->[client-ip]:53836 (ESTABLISHED)
    opennota 16458 opennota   72u  IPv6 43158889      0t0    TCP [myserver]:9000->[client-ip]:50512 (ESTABLISHED)
    opennota 16458 opennota   73u  IPv6 43155244      0t0    TCP [myserver]:9000->[client-ip]:64589 (ESTABLISHED)
    opennota 16458 opennota   74u  IPv6 43158891      0t0    TCP [myserver]:9000->[client-ip]:50520 (ESTABLISHED)
    opennota 16458 opennota   75u  IPv6 43159077      0t0    TCP [myserver]:9000->[client-ip]:53838 (ESTABLISHED)
    opennota 16458 opennota   76u  IPv6 43155330      0t0    TCP [myserver]:9000->[client-ip]:50257 (ESTABLISHED)
    opennota 16458 opennota   77u  IPv6 43155332      0t0    TCP [myserver]:9000->[client-ip]:50258 (ESTABLISHED)
    opennota 16458 opennota   78u  IPv6 43155334      0t0    TCP [myserver]:9000->[client-ip]:50259 (ESTABLISHED)
    opennota 16458 opennota   79u  IPv6 43158893      0t0    TCP [myserver]:9000->[client-ip]:50523 (ESTABLISHED)
    opennota 16458 opennota   80u  IPv6 43159079      0t0    TCP [myserver]:9000->[client-ip]:53837 (ESTABLISHED)
    opennota 16458 opennota   81u  IPv6 43158895      0t0    TCP [myserver]:9000->[client-ip]:50522 (ESTABLISHED)
    opennota 16458 opennota   82u  IPv6 43159081      0t0    TCP [myserver]:9000->[client-ip]:53835 (ESTABLISHED)
    opennota 16458 opennota   83u  IPv6 43159083      0t0    TCP [myserver]:9000->[client-ip]:53834 (ESTABLISHED)
    opennota 16458 opennota   84u  IPv6 43171822      0t0    TCP [myserver]:9000->[client-ip]:59842 (ESTABLISHED)
    opennota 16458 opennota   85u  IPv6 43174417      0t0    TCP [myserver]:9000->[client-ip]:55058 (ESTABLISHED)
    opennota 16458 opennota   86u  IPv6 43158897      0t0    TCP [myserver]:9000->[client-ip]:50521 (ESTABLISHED)
    opennota 16458 opennota   87u  IPv6 43174418      0t0    TCP [myserver]:9000->[client-ip]:55059 (ESTABLISHED)
    opennota 16458 opennota   88u  IPv6 43174419      0t0    TCP [myserver]:9000->[client-ip]:55063 (ESTABLISHED)
    opennota 16458 opennota   89u  IPv6 43174421      0t0    TCP [myserver]:9000->[client-ip]:55062 (ESTABLISHED)
    opennota 16458 opennota   90u  IPv6 43174423      0t0    TCP [myserver]:9000->[client-ip]:55061 (ESTABLISHED)
    opennota 16458 opennota   91u  IPv6 43174437      0t0    TCP [myserver]:9000->[client-ip]:55145 (ESTABLISHED)

The `[client-ip]` here is the same IP (they look like IPv4 ones, despite that `lsof` prints `IPv6`). The same is observed for other client addresses.

I use revel from the master branch, commit 7f4fb7444d9e.

    $ go version
    go version go1.4 linux/amd64

**Comment by anonx** [comment] 2015-01-04 02:16
Hey, @opennota. Is it a dev environment (`revel run ...`)? Or prod (`revel build ... & cd ... & ./run.sh`)?

**Comment by opennota** [comment] 2015-01-04 02:45
The latter.

**Comment by brendensoares** [comment] 2015-01-04 08:30
@anonx have you tried reproducing? I wonder if this is a Go 1.4 issue.

@opennota can you give us steps to reproduce. Does it happen with a brand new app? What commands do you run to reproduce the error? Have you tried on Go 1.3 as well?

Thanks.

**Comment by anonx** [comment] 2015-01-04 09:22
Yes, I tried. Here are the results:
```
opennota  26502 anonx    9u  IPv6 21601119      0t0  TCP *:9000 (LISTEN)
opennota  26502 anonx   10u  IPv6 21617160      0t0  TCP server:9000->client:50713 (ESTABLISHED)
opennota  26502 anonx   13u  IPv6 21616214      0t0  TCP server:9000->client:50714 (ESTABLISHED)
opennota  26502 anonx   14u  IPv6 21617162      0t0  TCP server:9000->client:50715 (ESTABLISHED)
opennota  26502 anonx   15u  IPv6 21616216      0t0  TCP server:9000->client:50716 (ESTABLISHED)
opennota  26502 anonx   16u  IPv6 21617164      0t0  TCP server:9000->client:50717 (ESTABLISHED)
opennota  26502 anonx   17u  IPv6 21617165      0t0  TCP server:9000->client:50718 (ESTABLISHED)
```
I stress tested both @opennota's app and sample app. From loads of requests, a few stay unclosed. I'm using go1.4. I'll try go1.3 and share the results here.

**Comment by opennota** [comment] 2015-01-04 10:47
I tried to reproduce it, but couldn't get *that many* unclosed connections. I got just a couple of them. BTW, after about 14 hours 74 of these connections (on the production server) are still ESTABLISHED (I `diff` ed lsof outputs to find unchanged lines).

**Comment by anonx** [comment] 2015-01-04 15:11
Well, it looks like this is not due to some kind of flaw in Revel code or something.
[Here](https://groups.google.com/forum/#!topic/golang-nuts/JFhGwh1q9xU) is a related discussion. `HTTP 1.1` `keep-alive` connections are just live for quite long time.

To check this hypothesis update your `init.go` and insert to line 37:
```go
var HeaderFilter = func(...) {
	...
	c.Response.Out.Header().Set("Connection", "close") // Line 37
	...
}
```
Thus, connections will be closed immediately.

But we still have to decide whether to use a timeout on server. Or come up with some other solution. Thoughts?

**Comment by opennota** [comment] 2015-01-04 15:33
I've added read and write timeouts:

``` diff
--- a/app/init.go
+++ b/app/init.go
@@ -16,6 +16,8 @@
 package app
 
 import (
+       "time"
+
        "github.com/jgraham909/revmgo"
        "github.com/revel/revel"
 )
@@ -37,4 +39,8 @@ func init() {
        }
        revel.OnAppStart(revmgo.AppInit)
        revel.OnAppStart(AppInit)
+       revel.OnAppStart(func() {
+               revel.Server.ReadTimeout = time.Minute
+               revel.Server.WriteTimeout = time.Minute
+       })
 }
```

**Comment by anonx** [comment] 2015-01-04 17:18
@opennota, http://www.stevesouders.com/blog/2008/03/20/roundup-on-parallel-connections/
> Section 8.1.4 of the HTTP/1.1 RFC says a “single-user client SHOULD NOT maintain more than 2 connections with any server or proxy.” The key here is the word “should.” Web clients don’t have to follow this guideline. IE8 isn’t the first to exceed this guideline. Opera and Safari hold that honor supporting 4 connections per server.

#### Number of connections per server by browsers:

|Browser |	HTTP/1.1    |	HTTP/1.0 |
|-----------|----------------|----------------|
| IE 6,7    | 	2 |	4 |
| IE 8       |	6 |	6 |
| Firefox 2| 	2 |	8 |
| Firefox 3 |	6 |	6 |
| Safari 3,4 |	4 |	4 |
| Chrome 1,2| 	6 |	? |
| Chrome 3 |	4 |	4 |
| Chrome 4+ |	6 |	? |
| iPhone 2  |	4 |	? |
| iPhone 3 |	6 |	? |
| iPhone 4 |	4 |	? |
| Opera 9.63,10.00alpha | 	4  |	4 |
| Opera 10.51+ 	| 8 | 	? |

**Comment by opennota** [comment] 2015-01-04 17:42
@anonx, 8 seems to be the maximum. Nowhere near 20+ simultaneous connections.

So far, multiple connections are still present on the server, but their number don't grow as it was before I set the timeouts.

**Comment by anonx** [comment] 2015-01-04 17:59
@opennota, Can browser reuse those connections after restart? Or after long lasting inactivity? Probably, it can't so it opens new connections (and old ones are neither closed not reused). I haven't dived into RFCs, specs, and browser docs, though. So, that's just my assumption.

@brendensoares, do you think Revel should have some timeouts built in? We have WS support, I'm not sure how that would affect it. But at least, this should be documented. Because, malicious clients (any clients with `F5` button) are able to DoS a website in minutes.
I wonder, does nginx help handle this problem? Keep-alive connections, http 1.1. @pushrax

**Comment by brendensoares** [comment] 2015-01-05 23:20
@anonx a Revel timeout seems wise. Nginx does manage [request timeouts](http://www.nginxtips.com/504-gateway-time-out-using-nginx/).

@opennota IE and other browsers probably have a minimum idle connections to an "active" domain and will probably open connections until it meets that minimum. It seems [browsers open a lot more than 8 simultaneous connections](http://www.browserscope.org/?category=network).

I see 2 problems that Revel has to handle directly when not using a front-end proxy like Nginx:
1. Manage the maximum number of [keep-alive requests](http://golang.org/pkg/net/http/#Server.SetKeepAlivesEnabled). We already [close each request](https://github.com/revel/revel/blob/master/server.go#L50), but the connection is the real issue, not the request.
2. Set a maximum number of simultaneous connections Revel will accept at once and reject the rest (i.e. after 32 requests, it [returns a 503](http://www.checkupdown.com/status/E503.html)). You could also not set a max and just let the requesting client wait or timeout itself.

DDoS is still possible, but at least it's configurable. It looks like @opennota's use of `ReadTimeout` will allow us to better control how long a connection exists before it meets its timeout deadline. FYI, [deadline is extended at the start of every request that a connection sends](https://codereview.appspot.com/7220076/diff/16001/src/pkg/net/http/server.go). See [this stackoverflow question](http://stackoverflow.com/questions/22493730/http-keep-alive-timeout-on-server).

**Comment by brendensoares** [comment] 2015-01-06 05:37
@opennota I don't understand how 1 client has 96 connections. What client is it? I've never seen that! Are they local connections or via the internet? Is it on a domain name or IP address?

**Comment by opennota** [comment] 2015-01-06 05:46
They were internet connections. The client's IP address was 188.233.143.xxx. A badly written bot, maybe? I don't know.

**Comment by brendensoares** [comment] 2015-01-06 05:54
@opennota if it was a bot, then that makes sense, since major browsers are coded to respect RFC guidelines (to some degree).

This does bring up a good conversation about limiting connections though. The easiest solution is toput a front-end proxy in front of Revel. @pedromorgan we should make this clear in the "deployment" section of the manual. Revel does NOT have connection/resource management and all production deployments should have a HTTP proxy that is properly configured in front of all Revel HTTP requests.

**Comment by anonx** [comment] 2015-01-06 07:10
@brendensoares 
> Manage the maximum number of keep-alive requests. We already close each request, but the connection is the real issue, not the request.

Would we start using **non** `keep-alive` when the number of `keep-alive` connections is exceeded?

>  Set a maximum number of simultaneous connections Revel will accept at once and reject the rest (i.e. after 32 requests, it returns a 503). You could also not set a max and just let the requesting client wait or timeout itself.

Isn't it how it works now? Except in your case the limitation is configured.

@opennota 

> Or, maybe, Revel can close an oldest connection when accepting a new one.

I think, that's what timeout is for. Not sure closing active connections is a good idea.


--------------------------------------------------------------------
Well, I think timeouts and proper documentation is all we can do. It is not a good idea to limit the number of connections per ip, as user with [82.148.97.69](https://en.wikipedia.org/wiki/User:82.148.97.69) wouldn't understand us. And other solutions are not effective against malicious users anyway.

It is possible to configure timeouts on operating system ([Linux example](http://www.cyberciti.biz/tips/linux-increasing-or-decreasing-tcp-sockets-timeouts.html)) rather than framework level. The same is relevant for the [number of connections](http://stackoverflow.com/questions/410616/increasing-the-maximum-number-of-tcp-ip-connections-in-linux).

**Comment by opennota** [comment] 2015-01-07 04:07
Well, I think the issue can be closed now.

**Closed** 2015-01-07 06:25 UTC
Labels: support
