### ISSUE TITLE
Templates escape html entities even if they are not escaped in the template itself

### ISSUE THREAD

**Issue by noway** [revel/revel#1137] opened 2017-03-12 11:56 UTC
For example:

```
<script type="text/template" id="online_tmpl">
	<span class="nickname nickname-logged-in <% if(event.A == true) { %>nickname-moderator<% } %> <%= (event.N == Nickname ? 'you' : '') %> ">
		<%= event.N %>
	</span>
</script>
```

Which is purely front end template.

Is rendered as 

```
<script type="text/template" id="online_tmpl">
	<span class="nickname nickname-logged-in <% if(event.A == true) { %>nickname-moderator<% } %> <%= (event.N == Nickname ? 'you' : '') %> ">
		&lt;%= event.N %>
	</span>
</script>
```

While they are expected to be exactly the same.

I could serve the content using Static.Serve (in that case issue is not present, because Static.Server is a dumb pipe), but I really would like to use back end revel templating for splitting up pages to modules.

**Comment by notzippy** [comment] 2017-03-12 15:49
Yup duplicate of #1128, I will bump the priority of that ticket

**Closed by notzippy** 2017-03-12 15:49 UTC
