### ISSUE TITLE
Revel 0.12 - Failed to load routes file when deployed

### ISSUE THREAD

**Issue by xoen** [revel/revel#911] opened 2015-03-27 13:50 UTC
Hi All,

I updated a couple of our apps to Revel 0.12 for various reasons.
I had [some problems](https://github.com/revel/revel/issues/909) related to the modules.

Now, despite the fact tests are passing and the app seems to run fine locally, once deployed it crashes miserably at start.

It seems revel doesn't find the config/routes file because it's looking for it under `$GOPATH/src/github.com/revel/modules/testrunner/` for some reason.

I changed the `app.config` as explained in the Release notes, just in case you were wondering.

Here the log of application start:
```
INFO  2015/03/27 13:31:14 revel.go:329: Loaded module static
INFO  2015/03/27 13:31:14 revel.go:329: Loaded module testrunner
INFO  2015/03/27 13:31:14 revel.go:206: Initialized Revel v0.12.0 (2015-03-25) for >= go1.3
INFO  2015/03/27 13:31:14 main.go:30: Running revel server
ERROR 2015/03/27 13:31:14 router.go:431: Failed to load routes file: open /app/.go/src/github.com/revel/modules/testrunner/conf/routes: no such file or directory
panic: Failed to load routes file: open /app/.go/src/github.com/revel/modules/testrunner/conf/routes: no such file or directory


goroutine 1 [running]:
log.(*Logger).Panicln(0xc20802f270, 0xc2080a9b60, 0x1, 0x1)
  /tmp/build/.goroot/src/log/log.go:207 +0xb7
github.com/revel/revel.func·045()
  /tmp/build/.go/src/github.com/revel/revel/router.go:431 +0x37b
github.com/revel/revel.runStartupHooks()
  /tmp/build/.go/src/github.com/revel/revel/server.go:135 +0x62
github.com/revel/revel.Run(0x1388)
  /tmp/build/.go/src/github.com/revel/revel/server.go:92 +0x237
main.main()
  /app/.go/src/github.com/mycompany/myapp/app/tmp/main.go:275 +0x2d0f

goroutine 2 [runnable]:
runtime.forcegchelper()
  /usr/local/go/src/runtime/proc.go:90
runtime.goexit()
  /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
  /usr/local/go/src/runtime/mgc0.go:82
runtime.goexit()
  /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
  /usr/local/go/src/runtime/malloc.go:712
runtime.goexit()
  /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
ERROR 2015/03/27 13:31:14 app.go:79: Error running: exit status 2
```

Thank you very much in advance for your help :)

**Comment by xoen** [comment] 2015-03-27 13:58
Oh, noooo, I closed the issue by mistake! Sorry for this.

**Comment by brendensoares** [comment] 2015-03-27 16:07
Sorry @xoen, but once an issue is closed, we can't answer it. Please open a new one.

Just kidding. I'm reading your post now.

**Comment by xoen** [comment] 2015-03-27 16:09
Ehehe, thanks (That button next to the "Comment" one keep tricking me!)

**Comment by brendensoares** [comment] 2015-03-27 16:10
> panic: Failed to load routes file: open /app/.go/src/github.com/revel/modules/testrunner/conf/routes: no such file or directory

1. Does this file exist?
2. How are you running revel?
3. What is in your `conf/routes`?

**Comment by xoen** [comment] 2015-03-27 16:20
Thanks for your help:

So:
1. Nope
2. I'm not quite sure because we're using Dokku and [this buildpack](https://github.com/revel/heroku-buildpack-go-revel). When I run the application locally I start it using `$ revel run github.com/mycompany/myapp` - It seems the buildpack is [doing the same](https://github.com/revel/heroku-buildpack-go-revel/blob/master/bin/release#L19).
3. A part from few routes there is also a `module:testrunner` directive.

**Comment by xoen** [comment] 2015-03-27 16:53
I managed to fix the problem just now. What I did was remove `module.testrunner = github.com/revel/modules/testrunner` from the `[staging]` and `[prod]` parts of the app.config (because we would run the tests only in `[dev]` environment anyway).

I'll deploy the other application to be sure everything is fine. I'll let you know ASAP.

Thanks very much for your help.

**Comment by brendensoares** [comment] 2015-03-27 17:02
Perhaps you need to remove `github.com/revel/modules` and `go get github/com/revel/modules` to retrieve the missing file? I'm not able to test this right now since I'm not at my workstation, but it's something to try.

**Comment by xoen** [comment] 2015-03-27 17:17
I successfully deployed the other app as well. It seems fine. So it looks like the problem is when you put this line:

`module.testrunner = github.com/revel/modules/testrunner`

in a non-dev part of the `app.conf`. Anyway, things seems to work on our staging server, hopefully I'll not have more problems when we'll promote the application to production :P

Do you rekon we should close this or do you think we should keep this open to update revel to be more robust in this scenario?

**Comment by brendensoares** [comment] 2015-03-27 17:24
We should test this further to see if we can reproduce the issue. Would you be able to create steps to reproduce this from a brand new Revel app (`revel new testrunnerbug`)?

**Comment by anonx** [comment] 2015-03-27 17:30
@brendensoares Yes, we can reproduce. The steps are simple. Just create an app and `revel build` it. Looks like that is related to #855. Testrunner module is loaded only when in `dev` mode. But `module:testrunner` is included in the `routes` by-default.
Should `revel build` remove unused routes? Or what should we do?

**Comment by anonx** [comment] 2015-03-27 17:41
Although we have the following check: https://github.com/revel/revel/blob/master/router.go#L296-L297
So, that might not be the case.

**Comment by brendensoares** [comment] 2015-03-27 17:41
How curious. Would you call this a bug or an enhancement? I lean toward bug.

Ps - @anonx do you work from home?

**Comment by anonx** [comment] 2015-03-27 17:43
@brendensoares It is definitely a bug, I think. At least I would expect `revel build` building a working version of app.

> do you work from home?

Why are you asking?

**Comment by xoen** [comment] 2015-03-27 17:44
It's actually interesting because from what I've seen [we check](https://github.com/revel/revel/blob/67891f91e7da2e524a8d1d8a27c6f481f021a445/revel.go#L333) if the `module.testrunner` configuration is there but we default to `github.com/revel/modules/testrunner`. So I'm not sure why the presence of that config would cause this behaviour.

**Comment by brendensoares** [comment] 2015-03-27 17:44
> Why are you asking?
Because you're able to run revel during the day. I'm at work so I just respond to issues as I have free time, but I can't run code.

**Comment by brendensoares** [comment] 2015-03-27 17:56
## TODO
- [ ] verify `testrunner` route is ignored in non-`dev` modes
- [ ] find root cause of `testrunner` error in non-`dev` modes

**Comment by anonx** [comment] 2015-03-27 18:48
@brendensoares The bug is not as critical as I though. Actually default app after `build` works as expected. Better steps to reproduce:
1. Include `module:something` route in your `app/routes`.
2. Add that module only to `prod` section (and `dev` if you want, but not to `DEFAULT`):
```ini
# there is no module.something in DEFAULT namespace
[prod]
module.something = path/to/something/module
```
3. Use `revel build`, `revel run [path] prod` doesn't have that error. So, looks like we have difference in order of calls in dev and prod again.

**Comment by anonx** [comment] 2015-03-27 19:25
One more observation. Config file:
```ini
[DEFAULT]
# no module.testrunner here...

[prod]
module.testrunner = github.com/revel/modules/testrunner
```
Routes:
```
module:testrunner
...
```
* `revel run github.com/username/project` will generate `app/tmp/main.go` with:
```go
revel.RegisterController(*TestRunner ...)
```
* `revel build github.com/username/project` doesn't include that call when generating `app/tmp/main.go`.

**Comment by brendensoares** [comment] 2015-03-27 19:33
@anonx good observations.

**Comment by anonx** [comment] 2015-03-27 19:51
So, here is the difference:
* We `run` our app in `dev` mode: https://github.com/revel/cmd/blob/a7b72c9afbff471c8c6c579f3b63780d2c478b12/revel/run.go#L39-L45
* We `build` it in `DEFAULT` mode: https://github.com/revel/cmd/blob/a7b72c9afbff471c8c6c579f3b63780d2c478b12/revel/build.go#L41 https://github.com/revel/revel/blob/67891f91e7da2e524a8d1d8a27c6f481f021a445/revel.go#L158

That's why all modules that are not in `DEFAULT` section will not be loaded when we `build`. Is that a bug? I'm not so sure now. We can try to build in `prod` mode though (although I think we shouldn't).

**Comment by anonx** [comment] 2015-04-17 10:31
This is not really a bug. #924 is related.

**Comment by jeevatkm** [comment] 2016-05-24 18:20
Yes, I agree with @alkchr this is not a bug. As per design Revel supports `modules/testrunner` in `dev` mode only.

As part recent PR https://github.com/revel/cmd/pull/14 and related fix around it. Revel will support `build` and `package` command with environment/mode value as an input ([cmd/build.go](https://github.com/revel/cmd/blob/develop/revel/build.go#L50) and [cmd/package.go](https://github.com/revel/cmd/blob/develop/revel/package.go#L47)), if not supplied it defaults to `prod`.

I'm closing this one, if we need to discuss about `testrunner` support for non-dev mode then can start a separate thread for discussion.

Thanks @alkchr

**Closed by jeevatkm** 2016-05-24 18:20 UTC
Labels: discuss, effort-minutes, priority-should, support, type-bug
