### ISSUE TITLE
RevelFramework.com  domain

### ISSUE THREAD

**Issue by pedromorgan** [revel/revel#857] opened 2015-01-18 01:25 UTC
I want to bring this up now..

But what we ideally want is the "domain" for revel moving forwards..

I got my little subdomain at http://revel-docs.daffodil.uk.com/
doing things..

But Ideally what we want is some applications that make revel work,,

Compile things, even test things..

So I kinda want to create the..
revel-samples.daffodil.uk.com site

Which will compile the samples and run as an application...
So that its interactive and live online...and reflext real app

Of course, this will be a revel application..
Get the idea ;-)))

in long term, we need a domain, but can be party to this with dedicates and jenkins and job..
hell revel should be able to run itself.. is the idea..

We cant get that outta github.. with the docs tied to their sandbox, cannot run code etc..
We need to seperate ourselves from the "markdown" and move more stuff into go code..
as lines of text.. 

Feedback appreciated on dog food..

Maybe the revel-devel.daffodil.uk.com is the first one 
and this check status of all git modules and latest patches et all..

**Comment by notzippy** [comment] 2015-01-18 01:33
Isn't this should be possible by using github and httrack. Have the dynamic site on a developer machine or something (this could be running anything you want). Use httrack to "mirror" that site to github.

**Comment by pedromorgan** [comment] 2015-01-18 01:36
Well yea kinda..

Snag is that with github.io, we are tied to "github" and jekyll etc..
so for example, I cant create a plugin and do clever "insecure=true" things..

But in the project, we want do insecure things like reading source files, and making webrequests..

So yes, its a gen docs things.. and like httrack we can rsync with some server..

**Comment by brendensoares** [comment] 2015-01-19 16:31
Do we want a custom domain for our Github Pages site or do we want a Go-based Revel site and then stop using Github Pages?

**Comment by pedromorgan** [comment] 2015-01-19 16:51
Snag with github, is that we cant create in ruby "with insecure".. tags..

Eg tags I wanna create are
{godcs "cache.NewCache"}

or
{see_also "controllers,cache,foo#bar"}

and clever stuff to do..

More I think about it, we should build the revel docs in revel itself.. all
we need is some templates
and a markdown parser.. etc.. wuite simple really..

Also this way, I thuink we could integrate the source code, issues etc..

**Comment by notzippy** [comment] 2015-01-19 19:18
I like the idea of revel hosting revel docs. It would be useful for a couple of reasons, 
*  It would showcase revel
*  You could build versioning information into the links, and update globally using app.conf
*  You could write tests to validate the documentation (check for broken links etc..).

**Comment by pedromorgan** [comment] 2015-03-23 23:53
Can we bring this to the front please..

But we need to focus more... and make it work..

so big questions are..
1) Where is the "revel-domain" gonna be and can we setit up now..
2) can we have installed revel + python fabric (sorry we need some py cos its simple)
3) I got it started at
https://github.com/pedromorgan/revel-www

At an upper level to that webservice..
we needs revel/meta..
Which I do not have write access, can clone.. its empty...
So perms or a simple read.me would be nice to get started..

Re revel-www..
Can i suggest that we create that project.. I can move
to revel/ so end users can see how revel uses itself ;-)
will be fun..
particular is we can embed the samples/ in revel also as prefix

**Comment by brendensoares** [comment] 2015-03-25 01:47
@pedromorgan Did you purchase revel.io? I remember that being expensive.

I don't want to use python. I'll setup nginx for shared hosting setup.

I purchased a Digital Ocean VPS for $5/mo and setup revelframework.com (we also have .ORG and revelgo.co). I'll install all the software tonight. Please provide your public SSH key and I'll add it so you can login to the VPS.

**Comment by brendensoares** [comment] 2015-03-25 14:31
Revel is running: http://revelframework.com:9000/

**Comment by pedromorgan** [comment] 2015-03-27 23:05
Need:
- www.revelframework.com = website + docs
- test.revelframework.com = next gen website + docs
- admin.reveltramework.com = admin panel for "revel"
- samples.revelframework.com/*/ = live sample sites

**Comment by pedromorgan** [comment] 2015-03-27 23:06
Am basically giving up on jekyll, its too restrictive..

and moving on with https://github.com/pedromorgan/revel-www

cos its gonna be more fun to make be a devil and make revel work the  way we want..

**Comment by pedromorgan** [comment] 2015-03-27 23:08
Whose got admin on the revel irc chat.. 

can we add a revel bot ?

**Comment by pedromorgan** [comment] 2015-03-27 23:47
Ok here's my plan..  for digestion and debate.. and these are quick notes cos me busy...

The goal is to have good docs both in code, and manual, and guide et all..
So the idea is to tie things together a bit more.. and hopefully this way get more contrib..
By tie together I mean versions of code, modules, quickstarts, deploys et all

We are limited with jekyll, and were a framework, so we have to revel in revel _ dogfood..
anyway were hitting the limits, and frustration of jekyll+github..

So my plan is to.. 
1) Dump Jekyll 
- so I started on the revel-www https://github.com/pedromorgan/revel-www
- but really I need a new repos called revel-docs
- and copy all the md docs into there...
- and dump completely the jekyll stuff.. so its almost pure markdown etc..
- even in directories/file  such as manual/intro.en.md 

2) Setup the revel app to parse a checkout of the revel-docs git
https://github.com/pedromorgan/revel-www/blob/master/conf/routes#L5
So steps so far are that..
the navigation is now in yamls files
and blackfriday md > html is kinda working...

3) workout the syntax highlights
- atmo the blackfriday is not workinyng with pygments amongst others..
- also cant figure out how to "parse" teh {%highlight go %} blocks and ```go so need help..

4) godoc.. + versioning
intention is to create git chekouts
a checkout of the revel/revel repos per tag.. is on the file system
eg
/git_checkouts/revel/0.12/*
/git_checkouts/revel/0.13/*
/git_checkouts/revel/0.14/*
ln -s /git_checkouts/revel/0.12/ /git_checkouts/revel/latest/

This way we can parse the files on the fly, instead of creating the files statically..

5) revel/meta
The idea of this is to hold an "index" of what is what across the project..
this includes logos, straplines, maintainers, admins, www_links,
et all..
All stuff is to be entered here, so a change here, automatically propogates across
the system, eg a new version, emergency relase notice, new logo.. 

5) modules/ documentation
A major part of my cunning stratergy is to convince the revel team
to allow documentaion md.files to be in the source..

This is certainly what I think would work with modules in partiulcar and is first target..

So the idea is that there would be
/modules/jobs/manual.md << the manual entry
/modules/jobs/tips.md << the tips and warnings page..

Bearing in mind that a developer can go and change this after a TWeak..
and is also versioned.. ie to the tag..
see #907

Anyway.. that should make the whole lot,, futurable imho..
well at least better than now..

we can then have fun such as notifications to IRC, a faw bot, live samples
international, and even an automatic self reminder or how olde revel is..
and UTC timezone fun

**Comment by brendensoares** [comment] 2015-04-02 05:52
@revel/core we need to schedule a meeting to get initiatives like the new revel website moving forward. How's 9pm PDT?

**Comment by notzippy** [comment] 2015-04-02 20:45
@brendensoares  What date ?

**Comment by brendensoares** [comment] 2015-04-03 20:16
@notzippy sorry, I was thinking Friday, today.

**Comment by brendensoares** [comment] 2015-04-03 20:37
@notzippy we have the next proposed meeting time in our wiki. So if any of us want to know when the next meeting is, it should always be proposed here: https://github.com/revel/revel/wiki/Meetings

**Comment by pedromorgan** [comment] 2015-04-05 23:37
Can I make a suggestion..

Whoever is in charge of the IRC,,,
can we stick a meeting on there....
And forget PST..
Make it UTC +/1 diff.. and comment

We need to keep irc alive

and ping me anytime anyones on.. 
sometimes u guys sneak in, whatever tod..
and all i want is a simple q+a

**Comment by pedromorgan** [comment] 2015-04-05 23:38
BTW:
Once we fire up the revel in revel on revel app..
we can can stick these in..  ;-)

**Comment by brendensoares** [comment] 2015-04-07 05:54
@pedromorgan no matter where we put the meeting time, the problem is getting everyone to meet. It's hard due to varying time zones and personal schedules. For example, becuase you're on UTC and we're on PDT, we have to find a day when some can meet at night and you meet with us in the morning. Then we have EST members too or @anonx in TX, USA.

We need to find a good day and stick to it.

I'm considering some form of agile dev sprints and tackling a small subset of features or fixes on a per week basis. To do that, we need to get organized first and that needs to happen soon.

@revel/core do you have any good ideas on how to coordinate schedules? Perhaps a shared Revel Google calendar?

**Comment by notzippy** [comment] 2015-04-07 17:54
@brendensoares a Shared calendar sounds good to me, we could create a hangout group for the core members as well. Also a shared workbook would be good as well, for group ideas, agendas, meeting notes..

**Comment by anonx** [comment] 2015-04-17 11:00
Hi @pedromorgan. Is any help with revel-www needed?

**Comment by DavidHunter** [comment] 2015-08-30 19:11
I think we should forget about IRC meetings. Just use github issues and accept any improvements.

**Comment by DavidHunter** [comment] 2015-08-30 19:55
Their should be a repository for revelframework.com. So we can contribute to it.

**Comment by brendensoares** [comment] 2015-09-05 21:26
@davidhunter contributions are welcome, but the core team needs to work together and in order to do that we need to communicate effectively and regularly.

@revel/core email revelframework AT gmail with your google account email so I can share a calendar and setup a hangout.

**Comment by pedromorgan** [comment] 2015-09-05 21:37
This is as far as I got with the app idea..

https://github.com/pedromorgan/revel-www

free Time, time time time is problem as usual.. ;-(

**Comment by jeevatkm** [comment] 2016-05-26 18:01
@pedromorgan - I would like to work with you on [revelframework.com](http://revelframework.com), please let me know your thoughts.

**Comment by pedromorgan** [comment] 2016-05-26 18:39
I started here..
https://github.com/pedromorgan/revelframework.com

Will look at it when i have time.. (its busy season here in Wales)

**Comment by jeevatkm** [comment] 2016-05-26 18:43
Thanks, I will have a look this repo.

**Comment by jeevatkm** [comment] 2016-05-29 01:11
I'm closing this one in-favour of revel/www#1

**Closed by jeevatkm** 2016-05-29 01:11 UTC
Labels: discuss, effort-hours, priority-should
