### ISSUE TITLE
Import of path failed modulePath

### ISSUE THREAD

**Issue by Dmdv** [revel/revel#1531] opened 2021-03-25 23:02 UTC
Following instruction, have this error on the run:
**GOVERSION=go1.16**

```
revel run my-app
Revel executing: run a Revel application
Downloading related packages ... completed.
ERROR 01:59:39  revel.go:107: Unable to execute error="Revel paths[error Failed to load module.  Import of path failed modulePath:github.com/revel/modules/static error:No files found in import path github.com/revel/modules/static ]"
```

**Comment by notzippy** [comment] 2021-03-27 16:47
Duplicate of #1528 This is fixed now, details on that issue

**Closed by notzippy** 2021-03-27 16:47 UTC
